/**
 * Configuración global de actions
 */
export const DO_ROUTE = "DO_ROUTE";
export const DO_IS_LOADING = "DO_IS_LOADING";
export const DO_REQUEST_API = "DO_REQUEST_API";
export const DO_LANDING = "DO_LANDING";
export const DO_LANDING_SUCCESS = "DO_LANDING_SUCCESS";
export const DO_LANDING_ERROR = "DO_LANDING_ERROR";
export const DO_PASO1 = "DO_PASO1";
export const DO_PASO2 = "DO_PASO2";
export const DO_GRACIAS = "DO_GRACIAS";
export const DO_MENSAJE = "DO_MENSAJE";
export const DO_NOTIFICATION_TOAST = "DO_NOTIFICATION_TOAST";
export const DO_NOTIFICATION_TOAST_RESET = "DO_NOTIFICATION_TOAST_RESET";
export const DO_BIOMETRIA = "DO_BIOMETRIA";
export const DO_INFORMACION_CUENTA = "DO_INFORMACION_CUENTA";
export const DO_CONFIRMAR_DOMICILIO_REAL = "DO_CONFIRMAR_DOMICILIO_REAL";
export const DO_CONFIRMAR_DOMICILIO_ALTERNATIVO =
  "DO_CONFIRMAR_DOMICILIO_ALTERNATIVO";
export const DO_CARGAR_OTRO_DOMICILIO = "DO_CARGAR_OTRO_DOMICILIO";
export const DO_CONFIRMAR_DATOS_FINALES = "DO_CONFIRMAR_DATOS_FINALES";
export const DO_FIRMAR_CONTRATO = "DO_FIRMAR_CONTRATO";
export const DO_REGISTRO = "DO_REGISTRO";
export const DO_PRESENCIAL = "DO_PRESENCIAL";
export const DO_DIGITAL = "DO_DIGITAL";
export const DO_PROCESAR_DATOS_PERSONALES = "DO_PROCESAR_DATOS_PERSONALES";
export const DO_PROCESAR_DOMICILIO_CORRESPONDENCIA =
  "DO_PROCESAR_DOMICILIO_CORRESPONDENCIA";
export const DO_CONSULTA_ESTADO_CLIENTE = "DO_CONSULTA_ESTADO_CLIENTE";
export const DO_CONSULTAR_DOMICILIO = "DO_CONSULTAR_DOMICILIO";
export const DO_VALIDAR_DOMICILIO = "DO_VALIDAR_DOMICILIO";
export const DO_VALIDAR_OTRO_DOMICILIO = "DO_VALIDAR_OTRO_DOMICILIO";
export const DO_PROCESAR_DOMICILIO = "DO_PROCESAR_DOMICILIO";
export const DO_ACTUALIZAR_DOMICILIO = "DO_ACTUALIZAR_DOMICILIO";
export const DO_ACTUALIZAR_OTRO_DOMICILIO = "DO_ACTUALIZAR_OTRO_DOMICILIO";
export const DO_COPIAR_DOMICILIO = "DO_COPIAR_DOMICILIO";
export const DO_RESETEAR_DOMICILIO = "DO_RESETEAR_DOMICILIO";
export const DO_RESETEAR_OTRO_DOMICILIO = "DO_RESETEAR_OTRO_DOMICILIO";
export const DO_CONSULTAR_CONTACTO = "DO_CONSULTAR_CONTACTO";
export const DO_PROCESAR_CONTACTO = "DO_PROCESAR_CONTACTO";
export const DO_CONSULTAR_DATOS_NORMATIVOS = "DO_CONSULTAR_DATOS_NORMATIVOS";
export const DO_ENVIO_MAIL_SITUACION_SO = "DO_ENVIO_MAIL_SITUACION_SO";
export const DO_ENVIO_MAIL_SITUACION_FATCA = "DO_ENVIO_MAIL_SITUACION_FATCA";
export const DO_RETROCEDER = "DO_RETROCEDER";
export const DO_LOGIN_VERIDAS = "DO_LOGIN_VERIDAS";
export const DO_POST_FRONT_DNI = "DO_POST_FRONT_DNI";
export const DO_POST_REVERSE_DNI = "DO_POST_REVERSE_DNI";
export const DO_POST_SELFIE = "DO_POST_SELFIE";
export const DO_POST_SELFIE_ALIVE = "DO_POST_SELFIE_ALIVE";
export const DO_POST_SELFIES = "DO_POST_SELFIES";
export const DO_POST_SELFIES_PROMISE = "DO_POST_SELFIES_PROMISE";
export const DO_ENVIO_CELULAR = "DO_ENVIO_CELULAR";
export const DO_ENVIO_SMS = "DO_ENVIO_SMS";
export const DO_REGISTRARSE = "DO_REGISTRARSE";
export const DO_CONSULTO_USUARIO = "DO_CONSULTO_USUARIO";
export const DO_CONSULTO_DOMICILIOS = "DO_CONSULTO_DOMICILIOS";
export const DO_OBTENER_CONTRATO = "DO_OBTENER_CONTRATO";
export const DO_CARGAR_DOMICILIO = "DO_CARGAR_DOMICILIO";
export const DO_ACTUALIZAR_DATOS_CLIENTE_DESDE_RENAPER =
  "DO_ACTUALIZAR_DATOS_CLIENTE_DESDE_RENAPER";
export const DO_CONFIRMAR_DATOS_INICIALES = "DO_CONFIRMAR_DATOS_INICIALES";
export const DO_VALIDAR_OTP_DATOS_DOMICILIOS =
  "DO_VALIDAR_OTP_DATOS_DOMICILIOS";
export const DO_CONFIRMAR_CONTACTO_CONSULTAR_DOMICILIOS =
  "DO_CONFIRMAR_CONTACTO_CONSULTAR_DOMICILIOS";
export const DO_ERROR_SELFIES = "DO_ERROR_SELFIES";
export const DO_CONSULTO_DOMICILIO_REAL_ALTERNATIVO =
  "DO_CONSULTO_DOMICILIO_REAL_ALTERNATIVO";
export const DO_MOCK_DATOS_RENAPER = "DO_MOCK_DATOS_RENAPER";
export const DO_FORMATEAR_OTRO_DOMICILIO = "DO_FORMATEAR_OTRO_DOMICILIO";
export const DO_OTP_MOCK = "DO_OTP_MOCK";
export const DO_ENVIAR_EMAIL_CONFIRMACION = "DO_ENVIAR_EMAIL_CONFIRMACION";
export const DO_GUARDAR_DOM_CORR = "DO_GUARDAR_DOM_CORR";
export const DO_CONSULTAR_DATOS_LABORALES = "DO_CONSULTAR_DATOS_LABORALES";
export const DO_PROCESAR_DATOS_LABORALES = "DO_PROCESAR_DATOS_LABORALES";
export const DO_CONFIRMAR_CONTACTO_CONSULTAR_LABORALES =
  "DO_CONFIRMAR_CONTACTO_CONSULTAR_LABORALES";
export const DO_CONFIRMAR_LABORALES_CONSULTAR_DOMICILIO =
  "DO_CONFIRMAR_LABORALES_CONSULTAR_DOMICILIO";
export const DO_APERTURA_CUENTA = "DO_APERTURA_CUENTA";
export const DO_GENERAR_OTP = "DO_GENERAR_OTP";
export const DO_REGISTRAR_USUARIOYCLAVE = "DO_REGISTRAR_USUARIOYCLAVE";
export const DO_VALIDAR_OTP = "DO_VALIDAR_OTP";
export const DO_AVANZAR_ETIQUETA_DIGITAL = "DO_AVANZAR_ETIQUETA_DIGITAL";
export const DO_ELEGIR_COMPANIA = "DO_ELEGIR_COMPANIA";
export const DO_DESENCRIPTAR = "DO_DESENCRIPTAR";
export const DO_AVANZAR_ETIQUETA_CLIENTE_OK = "DO_AVANZAR_ETIQUETA_CLIENTE_OK";
export const DO_ACTUALIZAR_ESTADO_TYC = "DO_ACTUALIZAR_ESTADO_TYC";
export const DO_AVANZAR_ETIQUETA_CLIENTE_ERROR =
  "DO_AVANZAR_ETIQUETA_CLIENTE_ERROR";
export const DO_RESTAURO_GRACIAS = "DO_RESTAURO_GRACIAS";
export const DO_RESTAURO_PASO4 = "DO_RESTAURO_PASO4";
export const DO_RESTAURO_PASO6 = "DO_RESTAURO_PASO6";
export const DO_RESTAURO_PASO7 = "DO_RESTAURO_PASO7";
export const DO_AUTODESTRUCCION = "DO_AUTODESTRUCCION";
export const DO_AUTODESTRUCCION_P1 = "DO_AUTODESTRUCCION_P1";
export const DO_AUTODESTRUCCION_P2 = "DO_AUTODESTRUCCION_P2";
export const DO_AUTODESTRUCCION_P3 = "DO_AUTODESTRUCCION_P3";
export const DO_AUTODESTRUCCION_P4 = "DO_AUTODESTRUCCION_P4";
export const DO_AUTODESTRUCCION_P5 = "DO_AUTODESTRUCCION_P5";
export const DO_AUTODESTRUCCION_V = "DO_AUTODESTRUCCION_V";
export const DO_AUTODESTRUCCION_I = "DO_AUTODESTRUCCION_I";
export const DO_REPROCESAR_DOMICILIO = "DO_REPROCESAR_DOMICILIO";
export const DO_DOMICILIO_EXISTENTE = "DO_DOMICILIO_EXISTENTE";
export const DO_AVANZAR_ETIQUETA_FORMULARIO_ERROR =
  "DO_AVANZAR_ETIQUETA_FORMULARIO_ERROR";
export const DO_FETCH_SUCURSALES = "DO_FETCH_SUCURSALES";
export const DO_ALATA_CLIENTE = "DO_ALATA_CLIENTE";
export const DO_VALIDAR_EN_SUCURSAL = "DO_VALIDAR_EN_SUCURSAL";
export const DO_AUTODESTRUCCION_PASO = "DO_AUTODESTRUCCION_PASO";
export const DO_PASO_INICIAL = "DO_PASO_INICIAL";
export const DO_RESTAURO_LABORALES = "DO_RESTAURO_LABORALES";
export const DO_RESTAURO_CUIL = "DO_RESTAURO_CUIL";
export const DO_ENVIO_MAIL_GERENTE = "DO_ENVIO_MAIL_GERENTE";
